### ISSUE TITLE
why 'log_px = (log_pz + delta_logp - log_qh_x  + log_pN)'?

### ISSUE THREAD

**Issue by qiangbo1222** [vgsatorras/en_flows#1]
in the compute loss code you define  log_px = (log_pz + delta_logp - log_qh_x  + log_pN), but in the original paper of ffjord: 'log_pz = log_pz - delta_logp '

is there a mistake? or did I miss something in the loss computing code

**Comment by vgsatorras** [comment]
Hi,

When estimating the log-likelihood in our model we also have to include a term for the dequantization of discrete features "log_qh_x" and another one for the number of nodes "log_pN". You can find all the terms you mentioned depicted in Figure 2 of our [paper](https://arxiv.org/pdf/2105.09016.pdf). These two additional terms are explained in more detail at the end of Section 4.

Best,
Victor

**Comment by qiangbo1222** [comment]
Thanks a lot, The explanation in the paper really helps me.
Best,
Bo
